spring.application.name=demo

#notification.type= sms
#
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:file:./data/h2db
#spring.datasource.username=h2db
#spring.datasource.password=1234
#spring.jpa.hibernate.ddl-auto=update

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
spring.datasource.username=postgres
spring.datasource.password=Long13@64

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

